import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { resetConfigForTests } from '../../src/config.js';
import { getRedis } from '../../src/redis.js';
import {
  assertMediaCapacityReservationLive,
  currentReservedMediaBytes,
  heartbeatMediaCapacityReservation,
  reconcileMediaCapacityReservation,
  releaseMediaCapacityReservation,
  reserveMediaCapacity,
} from '../../src/services/products/product-media-capacity.js';

const baseEnv = { ...process.env };

function overrideCapacityEnv(usable: number, reserve: number) {
  process.env.MEDIA_CAPACITY_USABLE_BYTES = String(usable);
  process.env.MEDIA_CAPACITY_RESERVE_BYTES = String(reserve);
  resetConfigForTests();
}

beforeEach(() => {
  overrideCapacityEnv(1_000, 0);
});

afterEach(() => {
  process.env = { ...baseEnv };
  resetConfigForTests();
});

describe('reserveMediaCapacity', () => {
  it('admits a reservation within budget', async () => {
    const r = await reserveMediaCapacity({ bytes: 400 });
    expect(r.bytes).toBe(400);
    expect(await currentReservedMediaBytes()).toBe(400);
  });

  it('rejects a reservation that would exceed usable-minus-reserve capacity', async () => {
    await reserveMediaCapacity({ bytes: 900 });
    await expect(reserveMediaCapacity({ bytes: 200 })).rejects.toMatchObject({
      status: 507,
      code: 'capacity_exceeded',
    });
    // The rejected attempt must not have been admitted.
    expect(await currentReservedMediaBytes()).toBe(900);
  });

  it('honors a configured reserve headroom below the raw usable bytes', async () => {
    overrideCapacityEnv(1_000, 300); // budget = 700
    await reserveMediaCapacity({ bytes: 700 });
    await expect(reserveMediaCapacity({ bytes: 1 })).rejects.toMatchObject({ code: 'capacity_exceeded' });
  });

  it('never admits concurrent reservations whose sum exceeds the budget', async () => {
    overrideCapacityEnv(1_000, 0);
    const attempts = Array.from({ length: 20 }, () => reserveMediaCapacity({ bytes: 100 }).catch((e) => e));
    const results = await Promise.all(attempts);
    const admitted = results.filter((r) => !(r instanceof Error));
    expect(admitted.length).toBeLessThanOrEqual(10); // 20 * 100 = 2000 > 1000 budget
    expect(await currentReservedMediaBytes()).toBe(admitted.length * 100);
  });
});

describe('heartbeatMediaCapacityReservation / reconcileMediaCapacityReservation', () => {
  it('renews TTL without changing the reserved amount, returning true (still live)', async () => {
    const r = await reserveMediaCapacity({ bytes: 200, ttlSeconds: 5 });
    await expect(heartbeatMediaCapacityReservation(r.id, 5)).resolves.toBe(true);
    expect(await getRedis().ttl(`media:capacity:res:${r.id}`)).toBeGreaterThan(0);
    expect(await currentReservedMediaBytes()).toBe(200);
  });

  it('returns false (not an error) for an already-released reservation', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(heartbeatMediaCapacityReservation(r.id)).resolves.toBe(false);
  });

  it('reconciles the reserved amount down to the real measured size, freeing budget, and returns true', async () => {
    const r = await reserveMediaCapacity({ bytes: 900 }); // worst-case estimate
    await expect(reconcileMediaCapacityReservation(r.id, 300)).resolves.toBe(true); // actual generated bytes
    expect(await currentReservedMediaBytes()).toBe(300);
    // Freed budget is now available to a new reservation.
    await expect(reserveMediaCapacity({ bytes: 600 })).resolves.toMatchObject({ bytes: 600 });
  });

  it('is a no-op (returns false) against an already-expired/released reservation, and never resurrects a TTL-less key (reviewer-p3 R2)', async () => {
    const r = await reserveMediaCapacity({ bytes: 900 });
    await releaseMediaCapacityReservation(r.id);
    await expect(reconcileMediaCapacityReservation(r.id, 300)).resolves.toBe(false);
    // A plain `SET ... KEEPTTL` (without `XX`) would have recreated the key
    // here with no TTL and no index entry — invisible to the budget and never
    // cleaned up. Prove the key genuinely does not exist at all.
    expect(await getRedis().exists(`media:capacity:res:${r.id}`)).toBe(0);
    expect(await currentReservedMediaBytes()).toBe(0);
  });
});

describe('assertMediaCapacityReservationLive', () => {
  it('resolves silently when the reservation is live', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await expect(assertMediaCapacityReservationLive(r.id)).resolves.toBeUndefined();
  });

  it('throws a typed 507 when the reservation is not live — the gate every final-byte-writing operation must pass (reviewer-p3 I2)', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(assertMediaCapacityReservationLive(r.id)).rejects.toMatchObject({
      status: 507,
      code: 'capacity_exceeded',
    });
  });
});

describe('releaseMediaCapacityReservation', () => {
  it('removes the reservation from the live total', async () => {
    const r = await reserveMediaCapacity({ bytes: 500 });
    await releaseMediaCapacityReservation(r.id);
    expect(await currentReservedMediaBytes()).toBe(0);
  });

  it('is idempotent', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(releaseMediaCapacityReservation(r.id)).resolves.toBeUndefined();
  });

  it('a shared reservation id used by two concurrent holders is only actually gone once the LAST holder releases it (reviewer-p4 shared-id theory)', async () => {
    // Reproduces the batch-publish shape product-moderation.ts's `approve` and
    // product-edits.ts's edit-approval flow both use: one reservation covers a
    // whole set of concurrent publishProductPhoto-style operations, and only
    // the outer batch coordinator ever calls release — never the individual
    // operations themselves. If any individual operation released on its own
    // instead, the first one to finish would kill the reservation while
    // others were still relying on it being live, exactly the spurious-507
    // theory reviewer-p4 raised. Audited every real release call site
    // (product-photos.ts, product-moderation.ts, product-edits.ts,
    // photo-upload.ts, edit-photo-upload.ts) — none currently do this, and
    // this test pins that invariant so a future change can't reintroduce it
    // silently.
    const r = await reserveMediaCapacity({ bytes: 1000 });

    let holderAFinished = false;
    let holderBFinished = false;

    const holderA = (async () => {
      await new Promise((resolve) => setTimeout(resolve, 20));
      // A slow "operation" checks liveness partway through its own work —
      // exactly what publishProductPhoto's assertMediaCapacityReservationLive
      // call does — and must still see the reservation as live, because nothing
      // has released it yet even though holder B may have already logically
      // "finished" its own portion of the batch.
      await expect(assertMediaCapacityReservationLive(r.id)).resolves.toBeUndefined();
      holderAFinished = true;
    })();

    const holderB = (async () => {
      // Finishes fast — the failure mode under the shared-id theory is
      // exactly a fast holder prematurely releasing while a slower one is
      // still mid-flight.
      holderBFinished = true;
    })();

    await Promise.all([holderA, holderB]);
    expect(holderAFinished).toBe(true);
    expect(holderBFinished).toBe(true);

    // Only now — after every concurrent holder is done — does the outer
    // batch coordinator release the shared reservation, exactly once.
    await releaseMediaCapacityReservation(r.id);
    await expect(heartbeatMediaCapacityReservation(r.id)).resolves.toBe(false);
  });
});

describe('currentReservedMediaBytes', () => {
  it('self-heals by dropping index entries whose reservation already expired', async () => {
    const r = await reserveMediaCapacity({ bytes: 50, ttlSeconds: 1 });
    // Simulate expiry without waiting a real second: delete the value key directly
    // but leave the index entry, exactly what a natural TTL expiry looks like.
    await getRedis().del(`media:capacity:res:${r.id}`);
    expect(await currentReservedMediaBytes()).toBe(0);
    // A subsequent reservation isn't blocked by the stale index entry.
    await expect(reserveMediaCapacity({ bytes: 999 })).resolves.toMatchObject({ bytes: 999 });
  });
});
