import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { resetConfigForTests } from '../../src/config.js';
import { getRedis } from '../../src/redis.js';
import {
  assertMediaCapacityReservationLive,
  currentReservedMediaBytes,
  heartbeatMediaCapacityReservation,
  reconcileMediaCapacityReservation,
  releaseMediaCapacityReservation,
  reserveMediaCapacity,
} from '../../src/services/products/product-media-capacity.js';

const baseEnv = { ...process.env };

function overrideCapacityEnv(usable: number, reserve: number) {
  process.env.MEDIA_CAPACITY_USABLE_BYTES = String(usable);
  process.env.MEDIA_CAPACITY_RESERVE_BYTES = String(reserve);
  resetConfigForTests();
}

beforeEach(() => {
  overrideCapacityEnv(1_000, 0);
});

afterEach(() => {
  process.env = { ...baseEnv };
  resetConfigForTests();
});

describe('reserveMediaCapacity', () => {
  it('admits a reservation within budget', async () => {
    const r = await reserveMediaCapacity({ bytes: 400 });
    expect(r.bytes).toBe(400);
    expect(await currentReservedMediaBytes()).toBe(400);
  });

  it('rejects a reservation that would exceed usable-minus-reserve capacity', async () => {
    await reserveMediaCapacity({ bytes: 900 });
    await expect(reserveMediaCapacity({ bytes: 200 })).rejects.toMatchObject({
      status: 507,
      code: 'capacity_exceeded',
    });
    // The rejected attempt must not have been admitted.
    expect(await currentReservedMediaBytes()).toBe(900);
  });

  it('honors a configured reserve headroom below the raw usable bytes', async () => {
    overrideCapacityEnv(1_000, 300); // budget = 700
    await reserveMediaCapacity({ bytes: 700 });
    await expect(reserveMediaCapacity({ bytes: 1 })).rejects.toMatchObject({ code: 'capacity_exceeded' });
  });

  it('never admits concurrent reservations whose sum exceeds the budget', async () => {
    overrideCapacityEnv(1_000, 0);
    const attempts = Array.from({ length: 20 }, () => reserveMediaCapacity({ bytes: 100 }).catch((e) => e));
    const results = await Promise.all(attempts);
    const admitted = results.filter((r) => !(r instanceof Error));
    expect(admitted.length).toBeLessThanOrEqual(10); // 20 * 100 = 2000 > 1000 budget
    expect(await currentReservedMediaBytes()).toBe(admitted.length * 100);
  });
});

describe('heartbeatMediaCapacityReservation / reconcileMediaCapacityReservation', () => {
  it('renews TTL without changing the reserved amount, returning true (still live)', async () => {
    const r = await reserveMediaCapacity({ bytes: 200, ttlSeconds: 5 });
    await expect(heartbeatMediaCapacityReservation(r.id, 5)).resolves.toBe(true);
    expect(await getRedis().ttl(`media:capacity:res:${r.id}`)).toBeGreaterThan(0);
    expect(await currentReservedMediaBytes()).toBe(200);
  });

  it('returns false (not an error) for an already-released reservation', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(heartbeatMediaCapacityReservation(r.id)).resolves.toBe(false);
  });

  it('reconciles the reserved amount down to the real measured size, freeing budget', async () => {
    const r = await reserveMediaCapacity({ bytes: 900 }); // worst-case estimate
    await reconcileMediaCapacityReservation(r.id, 300); // actual generated bytes
    expect(await currentReservedMediaBytes()).toBe(300);
    // Freed budget is now available to a new reservation.
    await expect(reserveMediaCapacity({ bytes: 600 })).resolves.toMatchObject({ bytes: 600 });
  });
});

describe('assertMediaCapacityReservationLive', () => {
  it('resolves silently when the reservation is live', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await expect(assertMediaCapacityReservationLive(r.id)).resolves.toBeUndefined();
  });

  it('throws a typed 507 when the reservation is not live — the gate every final-byte-writing operation must pass (reviewer-p3 I2)', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(assertMediaCapacityReservationLive(r.id)).rejects.toMatchObject({
      status: 507,
      code: 'capacity_exceeded',
    });
  });
});

describe('releaseMediaCapacityReservation', () => {
  it('removes the reservation from the live total', async () => {
    const r = await reserveMediaCapacity({ bytes: 500 });
    await releaseMediaCapacityReservation(r.id);
    expect(await currentReservedMediaBytes()).toBe(0);
  });

  it('is idempotent', async () => {
    const r = await reserveMediaCapacity({ bytes: 100 });
    await releaseMediaCapacityReservation(r.id);
    await expect(releaseMediaCapacityReservation(r.id)).resolves.toBeUndefined();
  });
});

describe('currentReservedMediaBytes', () => {
  it('self-heals by dropping index entries whose reservation already expired', async () => {
    const r = await reserveMediaCapacity({ bytes: 50, ttlSeconds: 1 });
    // Simulate expiry without waiting a real second: delete the value key directly
    // but leave the index entry, exactly what a natural TTL expiry looks like.
    await getRedis().del(`media:capacity:res:${r.id}`);
    expect(await currentReservedMediaBytes()).toBe(0);
    // A subsequent reservation isn't blocked by the stale index entry.
    await expect(reserveMediaCapacity({ bytes: 999 })).resolves.toMatchObject({ bytes: 999 });
  });
});
